import sys
import os

from manual_parser import (
    read_csv_manual,
    convert_types,
    calculate_summary,
    write_json as write_manual_json,
)

from pandas_parser import (
    read_csv_pandas,
    calculate_summary_pandas,
    write_json as write_pandas_json,
)


def compare_outputs(manual_summary: dict, pandas_summary: dict) -> str:
    """
    Compare the manual parser output with the pandas output
    and generate a markdown report.
    """

    report = "# Comparison Report\n\n"

    report += "## Objective\n\n"
    report += (
        "This report compares the summaries generated by the "
        "manual CSV parser and the pandas-based parser.\n\n"
    )

    report += "## Comparison\n\n"

    if manual_summary == pandas_summary:

        report += (
            "Both implementations produced equivalent results for:\n\n"
        )

        report += "- Total number of students\n"
        report += "- Number of submitted students\n"
        report += "- Number of missing submissions\n"
        report += "- Average score\n"
        report += "- Highest scorer\n"
        report += "- Lowest scorer among submitted students\n"
        report += "- Domain-wise average score\n"
        report += "- Students who did not submit\n"
        report += "- Students scoring below 5\n\n"

        report += (
            "The outputs match successfully. Any difference in "
            "dictionary key order does not affect the correctness "
            "of the generated summaries.\n\n"
        )

    else:

        report += (
            "The manual parser and pandas implementation produced "
            "different results.\n\n"
        )

    report += "## Conclusion\n\n"

    report += (
        "The manual parser correctly reproduces the same analysis "
        "performed using pandas for the given dataset."
    )

    return report


def main():

    if len(sys.argv) != 2:
        print("Usage:")
        print("python task_3/src/main.py task_3/data/submissions.csv")
        return

    input_file = sys.argv[1]

    manual_rows = read_csv_manual(input_file)
    manual_rows = convert_types(manual_rows)

    manual_summary = calculate_summary(manual_rows)

    df = read_csv_pandas(input_file)
    pandas_summary = calculate_summary_pandas(df)

    write_manual_json(
        manual_summary,
        "task_3/output/manual_summary.json",
    )

    write_pandas_json(
        pandas_summary,
        "task_3/output/pandas_summary.json",
    )

    report = compare_outputs(
        manual_summary,
        pandas_summary,
    )

    report_path = "task_3/output/comparison_report.md"

    os.makedirs(os.path.dirname(report_path), exist_ok=True)

    with open(report_path, "w", encoding="utf-8") as file:
        file.write(report)

    print("Task 3 completed successfully.")
    print("Outputs generated:")
    print("- task_3/output/manual_summary.json")
    print("- task_3/output/pandas_summary.json")
    print("- task_3/output/comparison_report.md")


if __name__ == "__main__":
    main()